### ISSUE TITLE
Single/Single Digit Addition and Subtraction

### ISSUE THREAD

**Issue by deb761** [deb761/Solstice#1]
Implement items 5-10 of the student flow:

1. Present single digit addition problem according to Problem Generation
2. Accept answer.
3. Accept submit/OK.
4. If answer is correct:
    1. Present Good Job screen.
    2. Clear screen after 2 seconds.
    3. Allow Student to clear screen.
8. Else:
    1. Presented with Oops Screen that shows correct answer.
    2. Clear screen after 2 seconds.
    3. Student can clear screen.
9. Store Results

**Comment by fraktalVision** [comment]
closed with commit 6859e50

**Comment by deb761** [comment]
Good job, guys.  Now all that is left is to update the Progress Chart.

Debbie
