### ISSUE TITLE
Cookie on logon screen

### ISSUE THREAD

**Issue by dinocizmic** [deb761/Solstice#23]
Cookie needs to be on the login screen

**Comment by MikeTheGreat** [comment]
Was there a commit associated with this bug fix?  Would you mind referencing that here?

Also - it looks like 696381321bb12cb1f5a8a91c97c0e05f14a63dec is the commit that fixed this, but I don't see an image file being added to it and I don't see a 'cookie-happy.png' file in the images directory.  I do see a 'happy-cookie.png' file, though.
