### ISSUE TITLE
Cookie image is too narrow in Oops page

### ISSUE THREAD

**Issue by Cascadia-LizFallin** [deb761/Solstice#24]
Dimensions are incorrect, and the picture is distorted vertically

**Comment by MikeTheGreat** [comment]
Hi Liz,
Would you mind going back and clarifying this a bit?
Stuff that seems useful to include would be:
The path to the page (either URL or, even better, the path to find the Oops.aspx page in the project)
The desired dimensions of the image (or a note specifying that the picture should not be resized, or that the width should be 10% less than it's unscaled size with the vertical dimension scaled to match, etc, etc)
Thanks!
--Mike

**Comment by Cascadia-LizFallin** [comment]
The picture is not correctly proportioned: the horizontal dimension seems proportionally smaller than the vertical dimensions, which makes the image look "squished" from side to side.
The path is:
1. Login as user = "emma", password = "emma10"
2. Click "Ready"
3. Answer the first problem incorrectly
4. Error message page appears, with image of Cookie at the bottom
5. Compared to the Cookie image on the Release 1 Presentation power point, the horizontal dimension appears proportionally smaller than the vertical dimension
6. Image is set in GameScreen.aspx.cs, line 81, as "images/cookie-sad.png" with no sizing

**Comment by Cascadia-LizFallin** [comment]
Hi Mike,

I've added a comment which includes the path, a better description, and the
possible location in the code where the image is set.

**Comment by MikeTheGreat** [comment]
This is AWESOME!!  Super-clear and yet still concise.  
(Also - that was an incredibly quick response! :)  )
Thanks!
--Mike

**Comment by Cascadia-LizFallin** [comment]
Dimensions corrected. FYI The dimensions are hardcoded in GameScreen.aspx.

**Comment by MikeTheGreat** [comment]
Can you reference the commit that closed this, please?

**Comment by MikeTheGreat** [comment]
It looks like 696381321bb12cb1f5a8a91c97c0e05f14a63dec is the relevant commit?

**Comment by Cascadia-LizFallin** [comment]
Committed in my fork, c45bcac1f1b367af31337aeafc0610b5206fe5df

**Comment by MikeTheGreat** [comment]
Thanks!
